# Generated by Django 5.2.4 on 2025-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='algoritmo',
            field=models.CharField(choices=[('SUM', 'Suma simple'), ('BDI', 'BDI'), ('BAI', 'BAI'), ('WHOQOL', 'WHOQOL'), ('SSI', 'SSI')], default='SUM', max_length=20),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('cuestionario', 'orden')},
        ),
    ]
