# Generated by Django 5.2.4 on 2025-08-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_opcion_options_alter_pregunta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='version',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PSICOLOGO', 'Psicólogo'), ('ESTUDIANTE', 'Estudiante')], db_index=True, default='ESTUDIANTE', max_length=15),
        ),
        migrations.AddIndex(
            model_name='cuestionario',
            index=models.Index(fields=['estado'], name='forms_cuest_estado_5b3465_idx'),
        ),
        migrations.AddIndex(
            model_name='cuestionario',
            index=models.Index(fields=['algoritmo'], name='forms_cuest_algorit_c7c012_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionevaluacion',
            index=models.Index(fields=['psicologo', 'estado'], name='forms_sesio_psicolo_fb34ff_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionevaluacion',
            index=models.Index(fields=['estudiante', 'estado'], name='forms_sesio_estudia_859f0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('sesion', 'pregunta'), name='uq_respuesta_por_sesion_pregunta'),
        ),
    ]
