# Generated by Django 5.2.4 on 2025-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_cuestionario_activo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cuestionario',
            name='forms_cuest_estado_5b3465_idx',
        ),
        migrations.RemoveIndex(
            model_name='cuestionario',
            name='forms_cuest_algorit_c7c012_idx',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
    ]
