# Generated by Django 5.2.4 on 2025-09-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_cuestionario_forms_cuest_estado_5b3465_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
