# Generated by Django 5.2.4 on 2025-09-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_cuestionario_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
