# Generated by Django 5.2.4 on 2025-10-11 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_cuestionario_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='opcion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opcion',
            name='es_otro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opcion',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='ayuda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='requerido',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='opciones_multiple',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='valor_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='valor',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_respuesta',
            field=models.CharField(choices=[('OPCION_SIMPLE', 'Opción (una)'), ('OPCION_MULTIPLE', 'Opción (varias)'), ('NUMERICA', 'Numérica'), ('TEXTO', 'Texto libre'), ('ESCALA', 'Escala (Likert)')], default='OPCION_SIMPLE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='opcion',
            constraint=models.UniqueConstraint(fields=('pregunta', 'orden'), name='uq_opcion_orden_por_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='pregunta',
            constraint=models.UniqueConstraint(fields=('cuestionario', 'orden'), name='uq_pregunta_orden_por_cuestionario'),
        ),
    ]
