# Generated by Django 5.2.4 on 2025-10-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_opcion_options_alter_pregunta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestasociodemografica',
            name='opcion_elegida',
        ),
        migrations.RemoveField(
            model_name='respuestasociodemografica',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestasociodemografica',
            name='estudiante',
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='algoritmo',
            field=models.CharField(choices=[('SUM', 'Suma simple'), ('NONE', 'Sin algoritmo')], default='SUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('published', 'Publicado')], default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='es_otro',
            field=models.BooleanField(default=False, help_text="Marcar si esta opción habilita un campo de texto 'Otro'"),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='valor',
            field=models.CharField(help_text="Valor a guardar en la BD (ej: '1', 'H', 'M', 'totalmente_desacuerdo')", max_length=100),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuraciones JSON para ciertos tipos (ej. min/max para escalas)'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_respuesta',
            field=models.CharField(choices=[('TEXTO', 'Texto Abierto'), ('NUMERICA', 'Número'), ('FECHA', 'Fecha'), ('SI_NO', 'Sí / No'), ('OPCION_UNICA', 'Opción Única (Radio)'), ('OPCION_MULTIPLE', 'Opción Múltiple (Checkbox)'), ('ESCALA', 'Escala Numérica (Likert)')], default='OPCION_UNICA', max_length=20),
        ),
        migrations.DeleteModel(
            name='OpcionSociodemografica',
        ),
        migrations.DeleteModel(
            name='PreguntaSociodemografica',
        ),
        migrations.DeleteModel(
            name='RespuestaSociodemografica',
        ),
    ]
