# Generated by Django 5.2.4 on 2025-10-19 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_remove_respuestasociodemografica_opcion_elegida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
