# Generated by Django 5.2.4 on 2025-10-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_cuestionario_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='archivo_propuesta',
            field=models.FileField(blank=True, null=True, upload_to='propuestas/'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='comentario_propuesta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cuestionario',
            unique_together={('codigo', 'version')},
        ),
    ]
