# Generated by Django 5.2.4 on 2025-10-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_cuestionario_archivo_propuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('published', 'Publicado')], default='draft', max_length=12),
        ),
    ]
