# Generated by Django 5.2.4 on 2025-10-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_cuestionario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='comentario_admin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('published', 'Publicado')], default='draft', max_length=12),
        ),
    ]
