# Generated by Django 5.2.4 on 2025-11-05 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionevaluacion',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesionevaluacion',
            name='psicologo',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'PSICOLOGO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_asignadas', to='forms.perfil'),
        ),
    ]
