# Generated by Django 5.2.4 on 2025-11-05 16:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_sesionevaluacion_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('version', models.CharField(default='1.0', max_length=24)),
                ('activo', models.BooleanField(default=True)),
                ('missing_policy', models.CharField(choices=[('skip', 'Omitir'), ('zero', 'Cero'), ('fail', 'Fallar')], default='skip', max_length=10)),
                ('normalizacion', models.CharField(choices=[('none', 'Sin normalizar'), ('0_100', 'Escala 0–100')], default='0_100', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_profiles', to='forms.cuestionario')),
            ],
            options={
                'unique_together': {('cuestionario', 'nombre', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='forms.sesionevaluacion')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.scoringprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('pregunta_desde', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pregunta_hasta', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('agregacion', models.CharField(choices=[('SUM', 'Suma'), ('MEAN', 'Promedio'), ('COUNT_GE', 'Contar >= umbral'), ('COUNT_LE', 'Contar <= umbral'), ('COUNT_BETWEEN', 'Contar entre [a,b]'), ('MAX', 'Máximo'), ('MIN', 'Mínimo'), ('WEIGHTED_SUM', 'Suma ponderada')], default='SUM', max_length=16)),
                ('peso', models.FloatField(default=1.0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='forms.scoringprofile')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
