# Generated by Django 5.2.4 on 2025-11-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_scoringprofile_calificacionsesion_scoringrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacionsesion',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='scoringprofile',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='scoringrule',
            old_name='params',
            new_name='num_map',
        ),
        migrations.RenameField(
            model_name='scoringrule',
            old_name='peso',
            new_name='weight',
        ),
        migrations.AlterUniqueTogether(
            name='scoringprofile',
            unique_together={('cuestionario', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='agregacion',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='pregunta_desde',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='pregunta_hasta',
        ),
        migrations.AddField(
            model_name='scoringprofile',
            name='algoritmo',
            field=models.CharField(choices=[('SUM', 'Suma'), ('AVG', 'Promedio')], default='SUM', max_length=10),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='q_from',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='q_to',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='tipo',
            field=models.CharField(choices=[('RANGO_PREGUNTAS', 'Rango de preguntas')], default='RANGO_PREGUNTAS', max_length=30),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='txt_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='calificacionsesion',
            name='breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='calificacionsesion',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='forms.scoringprofile'),
        ),
        migrations.AlterField(
            model_name='calificacionsesion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='forms.sesionevaluacion'),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionsesion',
            unique_together={('sesion', 'profile')},
        ),
        migrations.RemoveField(
            model_name='scoringprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scoringprofile',
            name='missing_policy',
        ),
        migrations.RemoveField(
            model_name='scoringprofile',
            name='normalizacion',
        ),
        migrations.RemoveField(
            model_name='scoringprofile',
            name='version',
        ),
    ]
