# Generated by Django 5.2.4 on 2025-11-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_rename_created_at_calificacionsesion_creado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringrule',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='calificacionsesion',
            name='breakdown',
        ),
        migrations.RemoveField(
            model_name='scoringprofile',
            name='algoritmo',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='tipo',
        ),
        migrations.AddField(
            model_name='calificacionsesion',
            name='detalle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='include_tipos',
            field=models.CharField(default='*', max_length=120),
        ),
        migrations.AlterField(
            model_name='calificacionsesion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacionsesion',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='forms.scoringprofile'),
        ),
        migrations.AlterField(
            model_name='calificacionsesion',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='scoringprofile',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='q_from',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='q_to',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
