# Generated by Django 5.2.4 on 2025-11-06 03:36

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_alter_scoringrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringprofile',
            name='algoritmo',
            field=models.CharField(choices=[('SUM', 'Suma'), ('AVG', 'Promedio')], default='SUM', max_length=10),
        ),
        migrations.AlterField(
    model_name='scoringprofile',
    name='creado',
    field=models.DateTimeField(default=timezone.now),
    preserve_default=False,
),
    ]
