# Generated by Django 5.2.4 on 2025-11-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_scoringprofile_algoritmo_alter_scoringprofile_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='auto_sumar_likert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scoringprofile',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
