# Generated by Django 5.2.4 on 2025-11-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_cuestionario_auto_sumar_likert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
