# Generated by Django 5.2.4 on 2025-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_cuestionario_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('PSICOLOGO', 'Psicólogo'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=20),
        ),
    ]
