# Generated by Django 5.2.4 on 2026-01-29 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuraciones JSON para ciertos tipos'),
        ),
        migrations.AlterField(
            model_name='sesionevaluacion',
            name='psicologo',
            field=models.ForeignKey(blank=True, limit_choices_to={'usuario__rol': 'PSICOLOGO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_asignadas', to='forms.perfil'),
        ),
    ]
