# Generated by Django 5.2.4 on 2026-02-07 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_alter_pregunta_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSociodemografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=120)),
                ('edad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)])),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('tiene_pareja', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('tiempo_relacion_meses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tipo_relacion', models.CharField(blank=True, choices=[('NOVIO', 'Novio(a)'), ('ESPOSO', 'Esposo(a)'), ('UNION_LIBRE', 'Unión libre'), ('FREE', 'Free'), ('AMIGOVIO', 'Amigovio'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('tipo_relacion_otro', models.CharField(blank=True, max_length=80, null=True)),
                ('tiene_hijos', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('cuantos_hijos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vive_semana', models.CharField(choices=[('PADRES', 'Padres'), ('PAREJA', 'Pareja'), ('PAREJA_HIJOS', 'Pareja e hijos'), ('AMIGOS', 'Amigos'), ('SOLO', 'Solo'), ('OTRO', 'Otro')], max_length=20)),
                ('vive_semana_otro', models.CharField(blank=True, max_length=80, null=True)),
                ('vive_fin', models.CharField(choices=[('PADRES', 'Padres'), ('PAREJA', 'Pareja'), ('PAREJA_HIJOS', 'Pareja e hijos'), ('AMIGOS', 'Amigos'), ('SOLO', 'Solo'), ('OTRO', 'Otro')], max_length=20)),
                ('vive_fin_otro', models.CharField(blank=True, max_length=80, null=True)),
                ('estado_civil_padres', models.CharField(choices=[('CASADOS', 'Casados'), ('DIVORCIADOS', 'Divorciados'), ('UNION_LIBRE', 'Unión libre'), ('SEPARADOS', 'Separados'), ('OTRO', 'Otro')], max_length=20)),
                ('estado_civil_padres_otro', models.CharField(blank=True, max_length=80, null=True)),
                ('escolaridad_padre', models.CharField(max_length=120)),
                ('escolaridad_madre', models.CharField(max_length=120)),
                ('ocupacion_padre', models.CharField(max_length=120)),
                ('ocupacion_madre', models.CharField(max_length=120)),
                ('trabaja_actualmente', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('depende_de', models.CharField(blank=True, max_length=180, null=True)),
                ('padece_enfermedad', models.CharField(blank=True, default='', max_length=180)),
                ('correo_opcional', models.EmailField(blank=True, max_length=254, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sociodemo', to='forms.perfil')),
            ],
        ),
    ]
