# Generated by Django 5.2.4 on 2026-02-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_encuestasociodemografica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncuestaSociodemografica',
        ),
    ]
