# Generated by Django 5.2.4 on 2026-02-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_delete_encuestasociodemografica'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='adscripcion',
            field=models.CharField(blank=True, choices=[('ICSA', 'Instituto de Ciencias de la Salud'), ('ICBI', 'Instituto de Ciencias Básicas e Ingeniería'), ('ICSHU', 'Instituto de Ciencias Sociales y Humanidades'), ('ICEA', 'Instituto de Ciencias Económico Administrativas'), ('ICAP', 'Instituto de Ciencias Agropecuarias'), ('IA', 'Instituto de Artes'), ('ES_ACTOPAN', 'Escuela Superior de Actopan'), ('ES_ATOTONILCO', 'Escuela Superior de Atotonilco de Tula'), ('ES_SAHAGUN', 'Escuela Superior de Ciudad Sahagún'), ('ES_TEPEJI', 'Escuela Superior de Tepeji del Río'), ('ES_TIZAYUCA', 'Escuela Superior de Tizayuca'), ('ES_TLAHUELILPAN', 'Escuela Superior de Tlahuelilpan'), ('ES_ZIMAPAN', 'Escuela Superior de Zimapán'), ('ES_APAN', 'Escuela Superior de Apan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('PSICOLOGO', 'Psicólogo')], default='ESTUDIANTE', max_length=15),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='semestre',
            field=models.IntegerField(blank=True, choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre'), (7, '7° Semestre'), (8, '8° Semestre'), (9, '9° Semestre'), (10, '10° Semestre'), (11, '11° Semestre'), (12, '12° Semestre')], null=True),
        ),
    ]
