# Generated by Django 5.2.4 on 2026-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_perfil_adscripcion_perfil_matricula_perfil_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
