# Generated by Django 6.0.2 on 2026-02-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_alter_perfil_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_respuesta',
            field=models.CharField(choices=[('TEXTO', 'Texto Abierto'), ('NUMERICA', 'Número'), ('FECHA', 'Fecha'), ('SI_NO', 'Sí / No'), ('OPCION_UNICA', 'Opción Única (Radio)'), ('OPCION_MULTIPLE', 'Opción Múltiple (Checkbox)'), ('ESCALA', 'Escala Numérica (Likert)'), ('ESCALA_SLIDER', 'Escala tipo slider'), ('ESCALA_SEMAFORO', 'Escala tipo semáforo')], default='OPCION_UNICA', max_length=20),
        ),
    ]
