# Generated by Django 6.0.2 on 2026-02-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_alter_pregunta_tipo_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='autores',
            field=models.CharField(blank=True, help_text='Ejemplo: García, López & Hernández (2022)', max_length=255),
        ),
    ]
