# Generated by Django 6.0.2 on 2026-03-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_alter_calificacionsesion_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='puntos_corte',
            field=models.TextField(blank=True, default='', help_text='Texto clínico de referencia (no se interpreta automáticamente).'),
        ),
    ]
