# Generated by Django 6.0.2 on 2026-03-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_cuestionario_puntos_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringprofile',
            name='engine',
            field=models.CharField(choices=[('AUTO', 'Motor automático (reglas SUM/AVG)'), ('WHOQOL', 'Motor clínico WHOQOL'), ('CASO30', 'Motor clínico CASO-30'), ('PANAS', 'Motor clínico PANAS')], default='AUTO', max_length=20),
        ),
    ]
