# Generated by Django 6.0.2 on 2026-03-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_scoringprofile_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='acepto_consentimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_consentimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
