# Generated by Django 6.0.2 on 2026-03-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_perfil_acepto_consentimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionevaluacion',
            name='notas_psicologo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
