# Generated by Django 5.2.4 on 2026-01-29 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0023_alter_pregunta_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('probabilidad', models.FloatField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('SIN_DATOS', 'Sin datos'), ('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto')], default='SIN_DATOS', max_length=20)),
                ('modelo_version', models.CharField(default='rl_v1', max_length=40)),
                ('actualizado', models.DateTimeField(default=django.utils.timezone.now)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediccion_riesgo', to='forms.perfil')),
            ],
        ),
    ]
