# Generated by Django 5.2.4 on 2026-01-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionriesgo',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
